/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : string,
  'vehicleType' : VehicleType,
  'customer' : CustomerInfo,
  'owner' : Principal,
  'scheduledTime' : bigint,
  'createdTime' : bigint,
  'location' : string,
  'batteryCapacity' : BatteryCapacity,
}
export type BatteryCapacity = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface CustomerInfo {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'SUV' : null } |
  { 'van' : null } |
  { 'truck' : null } |
  { 'sedan' : null } |
  { 'compact' : null } |
  { 'luxury' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<
    [CustomerInfo, string, VehicleType, BatteryCapacity, bigint],
    string
  >,
  'getAppointment' : ActorMethod<[string], [] | [Appointment]>,
  'getAppointmentsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<Appointment>
  >,
  'getAvailableAppointmentSlots' : ActorMethod<[], Array<bigint>>,
  'getBusinessInfo' : ActorMethod<
    [],
    {
      'hours' : string,
      'name' : string,
      'email' : string,
      'address' : string,
      'phone' : string,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getPrice' : ActorMethod<[VehicleType, BatteryCapacity], bigint>,
  'getServicedZipCodes' : ActorMethod<[], Array<string>>,
  'getSupportedBatteryCapacities' : ActorMethod<[], Array<string>>,
  'getSupportedVehicleTypes' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isZipCodeServiced' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointmentStatus' : ActorMethod<[string, string], undefined>,
  'uploadLogo' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];